### ISSUE TITLE
Multiple Answer

### ISSUE THREAD

**Issue by drow-ranger** [SerjoPepper/bot-brother#16]
Good night
I want to make a bot answer my 3 messages and at the end of the answer will combine the message I'm delivering.

> Example
> me> / unlock
> bot> what is your account?
> me> drow-ranger
> bot> what is your computer name?
> me> PC-99
> bot> what's your ticket number?
> me> TICKET-001
> bot> admin pls unlock drow-ranger on PC-99 with TICKET-001

is this possible? Please help

> bot.command('unlock')
> .invoke(function (ctx) {
>   ctx.data.user = ctx.meta.user;
>   return ctx.sendMessage('Hello <%=user.first_name%>. what is your account?');
> })
> .answer(function (ctx) {
>   ctx.data.answer = ctx.answer;
>   return ctx.sendMessage('User Account: <%=answer%>. what is your computer name?');
> });

so far I use the command above. but can only accept 1 message. Please help

**Comment by SerjoPepper** [comment]
Hello, you should create subcommands like this
```js
bot.command('unlock')
.invoke(function (ctx) {
  ctx.data.user = ctx.meta.user;
  return ctx.sendMessage('Hello <%=user.first_name%>. what is your account?');
})
.answer(function (ctx) {
  ctx.session.account = ctx.answer;
  return ctx.go('set_computer_name');
});

bot.command('set_computer_name')
.invoke(function (ctx) {
  ctx.data.account = ctx.session.account;
  return ctx.sendMessage('User Account: <%=account%>. what is your computer name?');
})
.answer(function (ctx) {
  ctx.session.computer_name = ctx.answer;
  return ctx.go('set_ticket_number')
});

bot.command('set_ticket_number')
.invoke(function (ctx) {
  return ctx.sendMessage("what's your ticket number?");
})
.answer(function (ctx) {
  ctx.data.ticket_number = ctx.answer;
  ctx.data.computer_name = ctx.session.computer_name;
  ctx.data.account = ctx.session.account;
  return ctx.sendMessage('admin pls unlock <%=account%> on <%=computer_name%> with <%=ticket_number%>'); 
});
```
