### ISSUE TITLE
How to reset a state?

### ISSUE THREAD

**Issue by lsndr** [SerjoPepper/bot-brother#5]
How to reset current state after first answer on command?

For example user need to add his name once:

(how it has to be)
U: /name
B: Write your name
U: John
B: Thanks, John.
U: Mike
....nothing happens

(how it is)
U: /name
B: Write your name
U: John
B: Thanks, John.
U: Mike
B: Thanks, Mike.
U: Pavel
B: Thanks, Mike.
..

These methods doesn't help:
context.go()
context.goParent()
context.goBack()
context.repeat()
context.end()

**Comment by SerjoPepper** [comment]
Hi, it works this way because the text interpreted as an answer. If you want to finish this command and go to other command, use `context.go`:

```
context.go('start')
```
