### ISSUE TITLE
BotBrother and asynchronous db

### ISSUE THREAD

**Issue by lsndr** [SerjoPepper/bot-brother#6]
Is it possible to use asynchronous db with BotBrother. As I understood callbacks must always return promises. But when I want to get some information from db and send it to user I can't return "sendmessage promise". So it making imposible to use async dbs.

Am I right?

**Comment by SerjoPepper** [comment]
You can use any async db. `Promise` is one type of handy interface for async actions.

```
bot.command('start').invoke(function (ctx) {
  return new Promise(function (resolve) {
    query_to_your_db(function () {
      ctx.sendMessage(...).then(resolve)
    })
  })
})
```
